# Superstore - Retail

In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv("../data/raw/superstore-tableau.csv")

In [3]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [5]:
# Creating unique data tables

customer = data[["Customer ID", "Customer Name", "Segment", "Country", "State", "City", "Postal Code", "Region"]].drop_duplicates()
product = data[["Product ID", "Category", "Sub-Category", "Product Name"]].drop_duplicates()
orders = data[["Customer ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Product ID", "Sales", "Quantity", "Discount", "Profit"]].drop_duplicates()
orders['Order Date'] = pd.to_datetime(orders['Order Date'], format = "mixed")
orders['Ship Date'] = pd.to_datetime(orders['Ship Date'], format = "mixed")

In [6]:
customer.head()

,Customer ID,Customer Name,Segment,Country,State,City,Postal Code,Region
0,CG-12520,Claire Gute,Consumer,United States,Kentucky,Henderson,42420,South
2,DV-13045,Darrin Van Huff,Corporate,United States,California,Los Angeles,90036,West
3,SO-20335,Sean O'Donnell,Consumer,United States,Florida,Fort Lauderdale,33311,South
5,BH-11710,Brosina Hoffman,Consumer,United States,California,Los Angeles,90032,West
12,AA-10480,Andrew Allen,Consumer,United States,North Carolina,Concord,28027,South

In [7]:
product.head()

,Product ID,Category,Sub-Category,Product Name
0,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
1,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...
3,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table
4,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System

In [8]:
orders.head()

,Customer ID,Order ID,Order Date,Ship Date,Ship Mode,Product ID,Sales,Quantity,Discount,Profit
0,CG-12520,CA-2016-152156,2016-08-11,2016-11-11,Second Class,FUR-BO-10001798,261.9600,2,0.00,41.9136
1,CG-12520,CA-2016-152156,2016-08-11,2016-11-11,Second Class,FUR-CH-10000454,731.9400,3,0.00,219.5820
2,DV-13045,CA-2016-138688,2016-12-06,2016-06-16,Second Class,OFF-LA-10000240,14.6200,2,0.00,6.8714
3,SO-20335,US-2015-108966,2015-11-10,2015-10-18,Standard Class,FUR-TA-10000577,957.5775,5,0.45,-383.0310
4,SO-20335,US-2015-108966,2015-11-10,2015-10-18,Standard Class,OFF-ST-10000760,22.3680,2,0.20,2.5164

In [9]:
# Let's check overall sales for the orders
print("Total orders:", len(orders['Order ID'].unique()))

Total orders: 5009